set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(ATHENA_TARGET_PROFILE "debian12-x86_64" CACHE STRING "Athena target profile")
set(ATHENA_TARGET_GLIBC_VERSION "2.36" CACHE STRING "Maximum supported runtime glibc")
set(ATHENA_X86_64_TARGET "x86_64-linux-gnu" CACHE STRING "Debian 12 x86_64 target triple")
set(ATHENA_X86_64_SYSROOT
    ""
    CACHE PATH
    "Optional Debian 12 x86_64 sysroot"
)

if(ATHENA_X86_64_SYSROOT)
    set(CMAKE_SYSROOT "${ATHENA_X86_64_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH "${ATHENA_X86_64_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()
